---
title: "Lab 5 Exercises"
author: "Jonathan Zau"
format: pdf
---

## Genes Dataset Exploration

```{r}
genes = read.delim("https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt") # get input file
head(genes, 20) # display first 20 rows
nrow(genes) # display how many rows (i.e. genes) are in this dataset
ncol(genes) # display how many columns (i.e. data points) are in this dataset
colnames(genes) # display the names of the columns (i.e. data points)
table(genes$State) # Displays number of each unique value in the "State" column
table(genes$State)/nrow(genes) # Calculates fraction of all genes that are upregulated, downregulated, or unchanged
```

## Plotting Genes Dataset

```{r}
library(ggplot2) # Dont forget to call ggplot2 first!
ggplot(data = genes, mapping = aes(x = Condition1, y = Condition2, col = State))+
  geom_point()+ # Plots data as points
  scale_color_manual(values = c("blue", "gray", "red"))+ # Changes color for levels in the data
  labs(
    title = "Gene Expression Changes Upon Drug Treatment",
    x = "Control (no drug)",
    y = "Drug Treatment")

ggsave("genes.pdf")
```

